# Generated by Django 2.2.16 on 2023-03-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(max_length=36, null=True, verbose_name='Код подтверждения'),
        ),
    ]
