# Generated by Django 2.2.16 on 2023-03-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230307_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(help_text='Введите описание тайтла', null=True, verbose_name='Описание тайтла'),
        ),
    ]
