# Generated by Django 2.2.16 on 2023-03-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20230307_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, help_text='Введите описание тайтла', null=True, verbose_name='Описание тайтла'),
        ),
    ]
